### ISSUE TITLE
_callee leads to failing typeGuard checks.

### ISSUE THREAD

**Issue by nicholasbraun** [epegzz/winston-dev-console#1]
When I log an object before checking its type via a typeGuard in typescript, the appended _callee property leads to a false negative type check.

Is it possible to delete the _callee property after logging?

**Comment by epegzz** [comment]
Hey there :)

This has been annoying me as well, but so far I had no luck removing it again. But I'll have another idea that I'll try out over the weekend 🤞

**Comment by epegzz** [comment]
Should be fixed now 😊

I ended up with a slightly hacky solution, but seems to work just fine 😅 

Released `v1.2.0`

**Comment by nicholasbraun** [comment]
Thanks! I'll check it out.
